# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:3.6.17-xenial 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  rest:
    build: ./
    restart: always
    depends_on:
      - mongo    
    ports:
      - 6575:8001
