# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:3.6.17-xenial 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  rest:
    build: ./
    restart: always
    environment:
      MM_MONGO_USR: root
      MM_MONGO_PASS: password
      MM_MONGO_HOST: mongo
      MM_MONGO_PORT: 27017
    depends_on:
      - mongo    
    ports:
      - 6576:8001
